"""Initial exercise library and program templates, migrated from the
original client-side (localStorage) version of IronCore. Each exercise
carries a target rep range so the double-progression engine in
logic.py has something to work against."""

# (name, muscle_group, min_reps, max_reps, increment_weight, tip)
_E = {
    "bench": ("Bench Press — بنش برس", "صدر", 6, 8, 2.5, "ثبّت كتفيك للخلف، قوس خفيف في أسفل الظهر"),
    "incline_db": ("Incline DB Press — مائل", "صدر علوي", 8, 12, 2.0, "زاوية 30–45°، تحكم في الهبوط"),
    "cable_fly": ("Cable Fly — فلاي كيبل", "صدر", 12, 15, 1.0, "ركّز على الانقباض الكامل"),
    "ohp": ("OHP — ضغط عسكري", "كتف أمامي", 6, 10, 2.5, "شدّ البطن، لا تقوس أسفل الظهر"),
    "lat_raise": ("Lateral Raise — رفع جانبي", "كتف جانبي", 15, 20, 1.0, "كوع خفيف الانحناء"),
    "tricep_push": ("Tricep Pushdown — تراي كيبل", "تراي", 10, 15, 1.0, "ثبّت الكوعين بجانب الجسم"),
    "oh_ext": ("Overhead Ext — تراي علوي", "تراي", 10, 15, 1.0, "كوع يشير للأعلى فقط"),
    "pullup": ("Pull-up / Lat Pulldown", "ظهر عريض", 6, 10, 2.0, "اجذب الكوعين للأسفل والخلف"),
    "bb_row": ("Barbell Row — سحب بار", "ظهر متوسط", 6, 8, 2.5, "ظهر مسطح موازٍ للأرض"),
    "seated_row": ("Seated Cable Row", "ظهر متوسط", 10, 12, 2.0, "اضغط لوحَي الكتف معاً"),
    "face_pull": ("Face Pull — فيس بول", "دالية خلفية", 15, 20, 1.0, "اسحب نحو الوجه"),
    "bb_curl": ("Barbell Curl — كيرل بار", "بايسبس", 8, 12, 1.0, "لا تأرجح الجسم"),
    "incline_curl": ("Incline DB Curl", "بايسبس", 10, 15, 1.0, "اطالة كاملة في الأسفل"),
    "squat": ("Squat — سكوات", "أرباعية / ردف", 6, 8, 2.5, "ركبة تتبع اتجاه الإصبع، عمق مناسب"),
    "rdl": ("Romanian Deadlift", "همسترينج / ردف", 8, 12, 2.5, "ظهر مسطح، دفع الوركين للخلف"),
    "leg_press": ("Leg Press — ليج برس", "أرباعية", 10, 15, 5.0, "لا تقفل الركبة في الأعلى"),
    "leg_curl": ("Leg Curl — كيرل ساق", "همسترينج", 10, 15, 2.0, "تحكم في الهبوط"),
    "leg_ext": ("Leg Extension — مد ساق", "أرباعية", 12, 20, 2.0, "اضغط في القمة ثانية كاملة"),
    "calf": ("Calf Raise — كالف", "ربلة", 15, 20, 2.0, "اطالة كاملة في الأسفل"),
    "incline_bb": ("Incline BB Press", "صدر علوي", 6, 8, 2.5, ""),
    "dips": ("Dips — ديبس", "صدر / تراي", 8, 12, 0.0, "أمل جسمك للأمام للتركيز على الصدر"),
    "pec_deck": ("Pec Deck / Butterfly", "صدر", 12, 15, 1.0, ""),
    "db_shoulder": ("DB Shoulder Press", "كتف", 8, 10, 1.0, ""),
    "cable_lat_raise": ("Cable Lateral Raise", "كتف جانبي", 15, 20, 1.0, ""),
    "skull": ("Skull Crushers — قاطعة", "تراي", 10, 12, 1.0, ""),
    "deadlift": ("Deadlift — ديدليفت", "ظهر كامل", 3, 6, 2.5, "الشكل الصحيح أولاً دائماً"),
    "chest_row": ("Chest Supported Row", "ظهر متوسط", 10, 12, 2.0, ""),
    "single_row": ("Single Arm DB Row", "ظهر عريض", 10, 12, 1.0, ""),
    "rear_delt": ("Rear Delt Fly", "دالية خلفية", 15, 20, 1.0, ""),
    "hammer_curl": ("Hammer Curl", "بايسبس", 10, 12, 1.0, ""),
    "preacher_curl": ("Preacher Curl", "بايسبس", 10, 15, 1.0, ""),
    "hack_squat": ("Hack Squat", "أرباعية", 8, 12, 2.5, ""),
    "bulgarian": ("Bulgarian Split Squat", "أرباعية / ردف", 10, 12, 1.0, "كل رجل على حدة"),
    "seated_leg_curl": ("Seated Leg Curl", "همسترينج", 12, 15, 2.0, ""),
    "hip_thrust": ("Hip Thrust — رفع الوركين", "ردف", 10, 15, 2.5, "اضغط الردف في القمة"),
    "plank": ("Plank — بلانك", "كور", 1, 1, 0.0, "بطن مشدود، جسم خط مستقيم (وقت بالثواني)"),
    "ab_wheel": ("Ab Wheel — عجلة البطن", "كور", 10, 15, 0.0, ""),
    "decline_press": ("Decline Press", "صدر سفلي", 10, 12, 2.0, ""),
    "shrugs": ("Shrugs — شراق", "شراوي", 10, 15, 2.5, ""),
    "front_raise": ("Front Raise", "كتف أمامي", 12, 15, 1.0, ""),
    "rear_delt_machine": ("Rear Delt Machine", "دالية خلفية", 15, 20, 2.0, ""),
}


def ex(key):
    n, m, mn, mx, inc, tip = _E[key]
    return {"name": n, "muscle_group": m, "min_reps": mn, "max_reps": mx,
            "increment_weight": inc, "tip": tip}


PROGRAMS = [
    {
        "name": "PPL — Push/Pull/Legs",
        "days": [
            {"name": "Push — صدر، كتف، تراي", "muscles": "صدر / كتف / تراي", "is_rest": False,
             "exercises": [(ex("bench"), 4), (ex("incline_db"), 3), (ex("cable_fly"), 3),
                           (ex("ohp"), 4), (ex("lat_raise"), 4), (ex("tricep_push"), 3), (ex("oh_ext"), 3)]},
            {"name": "Pull — ظهر وبايسبس", "muscles": "ظهر / بايسبس", "is_rest": False,
             "exercises": [(ex("pullup"), 4), (ex("bb_row"), 4), (ex("seated_row"), 3),
                           (ex("face_pull"), 3), (ex("bb_curl"), 3), (ex("incline_curl"), 3)]},
            {"name": "Legs — أرجل كامل", "muscles": "أرباعية / همسترينج / ردف", "is_rest": False,
             "exercises": [(ex("squat"), 4), (ex("rdl"), 3), (ex("leg_press"), 3),
                           (ex("leg_curl"), 3), (ex("leg_ext"), 3), (ex("calf"), 4)]},
            {"name": "Push 2 — إعادة", "muscles": "صدر / كتف / تراي", "is_rest": False,
             "exercises": [(ex("incline_bb"), 4), (ex("dips"), 3), (ex("pec_deck"), 3),
                           (ex("db_shoulder"), 4), (ex("cable_lat_raise"), 3), (ex("skull"), 3)]},
            {"name": "Pull 2 — إعادة", "muscles": "ظهر / بايسبس", "is_rest": False,
             "exercises": [(ex("deadlift"), 3), (ex("chest_row"), 3), (ex("single_row"), 3),
                           (ex("rear_delt"), 3), (ex("hammer_curl"), 3), (ex("preacher_curl"), 3)]},
            {"name": "Legs 2 + Core", "muscles": "أرجل / كور", "is_rest": False,
             "exercises": [(ex("hack_squat"), 4), (ex("bulgarian"), 3), (ex("seated_leg_curl"), 3),
                           (ex("hip_thrust"), 4), (ex("plank"), 3), (ex("ab_wheel"), 3)]},
            {"name": "🧘 راحة — Recovery", "muscles": "", "is_rest": True, "exercises": []},
        ],
    },
    {
        "name": "Upper/Lower (4 أيام)",
        "days": [
            {"name": "Upper A — علوي أ", "muscles": "صدر / ظهر / كتف / ذراع", "is_rest": False,
             "exercises": [(ex("bench"), 4), (ex("bb_row"), 4), (ex("ohp"), 3),
                           (ex("pullup"), 3), (ex("tricep_push"), 3), (ex("bb_curl"), 3)]},
            {"name": "Lower A — سفلي أ", "muscles": "أرجل", "is_rest": False,
             "exercises": [(ex("squat"), 4), (ex("rdl"), 3), (ex("leg_press"), 3),
                           (ex("leg_curl"), 3), (ex("calf"), 4)]},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
            {"name": "Upper B — علوي ب", "muscles": "صدر / ظهر / كتف", "is_rest": False,
             "exercises": [(ex("incline_db"), 4), (ex("pullup"), 4), (ex("db_shoulder"), 3),
                           (ex("seated_row"), 3), (ex("lat_raise"), 4), (ex("face_pull"), 3)]},
            {"name": "Lower B — سفلي ب", "muscles": "أرجل / كور", "is_rest": False,
             "exercises": [(ex("deadlift"), 3), (ex("hack_squat"), 3), (ex("hip_thrust"), 4),
                           (ex("leg_ext"), 3), (ex("plank"), 3)]},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
        ],
    },
    {
        "name": "Bro Split (5 أيام)",
        "days": [
            {"name": "الصدر — Chest", "muscles": "صدر", "is_rest": False,
             "exercises": [(ex("bench"), 5), (ex("incline_db"), 4), (ex("decline_press"), 3),
                           (ex("cable_fly"), 3), (ex("dips"), 3)]},
            {"name": "الظهر — Back", "muscles": "ظهر", "is_rest": False,
             "exercises": [(ex("deadlift"), 4), (ex("pullup"), 4), (ex("bb_row"), 4),
                           (ex("seated_row"), 3), (ex("face_pull"), 3)]},
            {"name": "الكتف — Shoulders", "muscles": "كتف", "is_rest": False,
             "exercises": [(ex("ohp"), 4), (ex("db_shoulder"), 3), (ex("lat_raise"), 5),
                           (ex("front_raise"), 3), (ex("rear_delt_machine"), 4), (ex("shrugs"), 3)]},
            {"name": "الأرجل — Legs", "muscles": "أرجل", "is_rest": False,
             "exercises": [(ex("squat"), 5), (ex("rdl"), 4), (ex("leg_press"), 3),
                           (ex("leg_curl"), 4), (ex("hip_thrust"), 3), (ex("calf"), 5)]},
            {"name": "الذراع — Arms", "muscles": "بايسبس / تراي", "is_rest": False,
             "exercises": [(ex("bb_curl"), 4), (ex("incline_curl"), 3), (ex("preacher_curl"), 3),
                           (ex("skull"), 4), (ex("tricep_push"), 3), (ex("hammer_curl"), 3)]},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
        ],
    },
    {
        "name": "Full Body (3 أيام)",
        "days": [
            {"name": "Full Body A", "muscles": "كامل الجسم", "is_rest": False,
             "exercises": [(ex("squat"), 3), (ex("bench"), 3), (ex("bb_row"), 3),
                           (ex("ohp"), 2), (ex("rdl"), 2), (ex("bb_curl"), 2), (ex("tricep_push"), 2)]},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
            {"name": "Full Body B", "muscles": "كامل الجسم", "is_rest": False,
             "exercises": [(ex("deadlift"), 3), (ex("incline_db"), 3), (ex("pullup"), 3),
                           (ex("db_shoulder"), 2), (ex("leg_press"), 2), (ex("hammer_curl"), 2), (ex("dips"), 2)]},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
            {"name": "Full Body C", "muscles": "كامل الجسم", "is_rest": False,
             "exercises": [(ex("hack_squat"), 3), (ex("dips"), 3), (ex("seated_row"), 3),
                           (ex("lat_raise"), 3), (ex("hip_thrust"), 3), (ex("face_pull"), 2), (ex("ab_wheel"), 3)]},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
            {"name": "🧘 راحة", "muscles": "", "is_rest": True, "exercises": []},
        ],
    },
]
